import type { Metadata } from "next";
import "./globals.css";
import "react-loading-skeleton/dist/skeleton.css";

import 'react-toastify/dist/ReactToastify.css';

import { Poppins } from "next/font/google";
import QueryClientLayout from "./QueryClientLayout";
import AuthLayout from "./AuthLayout";

const inter = Poppins({ subsets: ["latin"], weight: ["500"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <AuthLayout>
          <QueryClientLayout>
            {children}
          </QueryClientLayout>
        </AuthLayout>
      </body>
    </html>
  );
}
