import type { Metadata } from "next";
import "./globals.css";
import NavbarMobile from "@/components/navbar/NavbarMobile";
import 'react-loading-skeleton/dist/skeleton.css'

import { Poppins } from "next/font/google";

const inter = Poppins({ subsets: ["latin"], weight: ["500"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} p-5 antialiased`}
      >
          {children}
      </body>
    </html>
  );
}
